export const categoryColorOptions = [
  '#22C55E',
  '#34D399',
  '#60A5FA',
  '#F59E0B',
  '#F472B6',
  '#A78BFA',
  '#FB7185',
  '#F97316',
  '#94A3B8',
  '#3DD68C',
  '#7C5CFF',
] as const;

export const bankIconOptions = [
  'shapes',
  'cart-shopping',
  'store',
  'utensils',
  'mug-saucer',
  'train',
  'bus',
  'taxi',
  'gas-pump',
  'house',
  'city',
  'bolt',
  'wifi',
  'mobile-screen-button',
  'gauge-high',
  'car',
  'shield-halved',
  'heart-pulse',
  'pills',
  'stethoscope',
  'film',
  'champagne-glasses',
  'bag-shopping',
  'shirt',
  'laptop',
  'gift',
  'plane',
  'book-open',
  'dumbbell',
  'paw',
  'baby',
  'pump-soap',
  'receipt',
  'wallet',
  'piggy-bank',
  'building-columns',
  'gamepad',
  'grip',
] as const;

export const categoryIconOptions = [
  ...bankIconOptions,
  'screwdriver-wrench',
  'music',
  'money-bill-trend-up',
  'money-bill-transfer',
  'right-left',
  'briefcase',
  'chart-line',
  'sack-dollar',
  'brand:mobilepay',
  'brand:spotify',
  'brand:apple-music',
  'brand:youtube-music',
  'brand:youtube',
  'brand:netflix',
  'brand:steam',
  'brand:playstation',
  'brand:paypal',
  'brand:google-pay',
  'brand:apple-pay',
  'brand:uber',
  'brand:airbnb',
  'brand:booking',
  'brand:ikea',
  'brand:reddit',
  'brand:tiktok',
  'brand:visa',
  'brand:mastercard',
] as const;
