export const categoryColorOptions = [
  '#34D399',
  '#60A5FA',
  '#F59E0B',
  '#F472B6',
  '#A78BFA',
  '#FB7185',
  '#F97316',
  '#94A3B8',
  '#3DD68C',
  '#7C5CFF',
] as const;

export const categoryIconOptions = [
  'shape-outline',
  'cart-outline',
  'storefront-outline',
  'silverware-fork-knife',
  'coffee-outline',
  'train-car',
  'bus',
  'taxi',
  'gas-station-outline',
  'home-outline',
  'home-city-outline',
  'flash-outline',
  'wifi',
  'cellphone',
  'meter-gas-outline',
  'car-outline',
  'shield-car',
  'heart-pulse',
  'pill',
  'stethoscope',
  'movie-open-outline',
  'party-popper',
  'shopping-outline',
  'tshirt-crew-outline',
  'laptop',
  'gift-outline',
  'airplane',
  'book-open-variant',
  'dumbbell',
  'paw-outline',
  'baby-face-outline',
  'lotion-outline',
  'receipt-text-outline',
  'wallet-outline',
  'piggy-bank-outline',
  'bank-outline',
  'gamepad-variant-outline',
  'dots-grid',
] as const;
